# Generated by Django 4.2.9 on 2026-04-05 06:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('inv_type', models.CharField(choices=[('SIP', 'SIP'), ('FD', 'Fixed Deposit'), ('PPF', 'PPF'), ('Stocks', 'Stocks'), ('Gold', 'Gold'), ('Crypto', 'Crypto'), ('RD', 'Recurring Deposit'), ('Savings Account', 'Savings Account'), ('NPS', 'NPS'), ('Other', 'Other')], db_column='type', default='SIP', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'savings',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='savings_user_id_b71944_idx'), models.Index(fields=['user', 'inv_type'], name='savings_user_id_5a8f00_idx')],
            },
        ),
    ]
