# Generated by Django 4.2.9 on 2026-04-05 06:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Finance', 'Finance'), ('Learning', 'Learning'), ('Skill', 'Skill'), ('Career', 'Career'), ('Personal', 'Personal'), ('Travel', 'Travel'), ('Business', 'Business')], default='Finance', max_length=15)),
                ('target', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('current', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('deadline', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals',
                'ordering': ['deadline', '-created_at'],
                'indexes': [models.Index(fields=['user', 'deadline'], name='goals_user_id_04f669_idx'), models.Index(fields=['user', 'category'], name='goals_user_id_4d2e0e_idx')],
            },
        ),
    ]
