# Generated by Django 4.2.9 on 2026-04-05 06:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('Online Course', 'Online Course'), ('YouTube', 'YouTube'), ('Book', 'Book'), ('Podcast', 'Podcast'), ('Documentation', 'Documentation'), ('Mentor', 'Mentor'), ('Other', 'Other')], default='Online Course', max_length=20)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='In Progress', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_sessions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='learning_se_user_id_c3be30_idx'), models.Index(fields=['user', 'status'], name='learning_se_user_id_d61245_idx')],
            },
        ),
    ]
