# Generated by Django 4.2.9 on 2026-04-05 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='trial', max_length=12)),
                ('plan', models.CharField(blank=True, choices=[('monthly', 'Monthly - ₹199'), ('yearly', 'Yearly  - ₹1,999')], default='monthly', max_length=8)),
                ('razorpay_sub_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('razorpay_cust_id', models.CharField(blank=True, max_length=100)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('subscription.activated', 'Activated'), ('subscription.charged', 'Charged'), ('subscription.cancelled', 'Cancelled'), ('subscription.expired', 'Expired'), ('subscription.halted', 'Halted'), ('payment.failed', 'Payment Failed')], max_length=50)),
                ('razorpay_event_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'payment_events',
                'ordering': ['-processed_at'],
            },
        ),
    ]
